language: cpp
addons:
  apt:
    packages:
    - libxml2-dev
    - libxml2-utils
    - libboost-all-dev
    - libprotobuf-dev
    - protobuf-compiler
    - doxygen
    - graphviz
script:
  - cd build
  - cmake -DPACKAGE=on ..
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 make test
  - make package

