name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      max-parallel: 5
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies (Linux)
      run: sudo apt-get install -y libboost-all-dev libxml2-dev libxml2-utils libreadline6-dev libprotobuf-dev protobuf-compiler doxygen graphviz
      if: matrix.os == 'ubuntu-latest'
    - name: configure
      run: cmake -DPACKAGE=on ..
      working-directory: ./build
    - name: make
      run: make
      working-directory: ./build
    - name: make test
      run: make test
      working-directory: ./build
    - name: Create package
      run: make package
      working-directory: ./build
